# Import
from time import sleep
from painutilities import *

# Funktion Kapitel 4
def exec_chapter4(sprache, short_delay = 1, long_delay = 2):
    
    # Deutsch
    if sprache == 1:
        
        print('Komm mit, wir zeigen dir wo wir wohnen\n')
        sleep(short_delay)
        print('Erzähler: Sie liefen ein paar Minuten bis sie zu einem riesigen Abgrund gekommen sind\n')
        sleep(short_delay)
        print('Faeren: Das was du hier siehst ist unsere Stadt\n')
        sleep(short_delay)
        print('Penarrow: Wow die ist ja riesig\n')
        sleep(short_delay)
        print('Faeren: Ja aber das ist nur ein Teil davon. Das meiste ist unterirdisch, da wir ziemlich oft angegriffen werden\n')
        sleep(long_delay)
        print('Penarrow: Wer greift euch denn an, niemand kennt doch diesen Ort hier\n')
        sleep(long_delay)
        print('Faeren: Drachen und weitere Wesen greifen uns an\n')
        sleep(short_delay)
        print('Penarrow: Hahaha ja genau wer es glaubt\n')
        sleep(long_delay)
        print('Faeren: Doch so ist es und leider können wir uns nicht wehren\n')
        sleep(long_delay)
        print('Aber eine Legende besagt, dass eines Tages ein Halbmensch kommt und den Drachen tötet\n')
        sleep(long_delay)
        print('Zum Glück bin ich nur ein Mensch und kein Halbmensch\n')
        
        # Enter und Konsole clearen
        nextstep()
        
        print('Faeren: Das werden wir ja sehen\n')
        sleep(short_delay)
        print('Die Legende besagt auch, wenn du ein spezielles Ritual machst,\n')
        sleep(long_delay)
        print('bekommst du spezielle Fähigkeiten\n')
        sleep(short_delay)
        print('Penarrow: Was für Fähigkeiten?\n')
        sleep(short_delay)
        print('Faeren: Wissen es nicht\n')
        sleep(short_delay)
        print('Bis jetzt ist die Legende nicht in Erfüllung gegangen\n')
        sleep(long_delay)
        print('Wir hoffen, dass du das Ritual mal machen könntest\n')
        sleep(short_delay)
        print('Penarrow: Was muss man denn beim Ritual machen?\n')
        sleep(short_delay)
        print('Faeren: Du musst einen speziellen Trank aus Kräutern trinken\n')
        sleep(short_delay)
        print('Penarrow: Und das war es? mehr nicht?\n')
        sleep(short_delay)
        print('Faeren: Wenn du der Auserwählte bist ja\n')
        sleep(short_delay)
        print('Penarrow: Und wenn nicht?\n')
        sleep(short_delay)
        print('Faeren: Dann stirbst du\n')
        sleep(short_delay)
        print('Penarrow: Hab ich eine Wahl?\n')
        sleep(short_delay)
        print('Faeren: Ja, die hast du\n')
        sleep(short_delay)
        print('Willst du es machen?\n')
        sleep(short_delay)
    
    # Englisch
    elif sprache == 2:
        print('Come with us, we can show you where we live\n')
        sleep(short_delay)
        print('Narrator: They were walking for a few minutes util they reached a cliff\n')
        sleep(short_delay)
        print('Faeren: What you see here is our town\n')
        sleep(short_delay)
        print('Penarrow: Its so big\n')
        sleep(short_delay)
        print('Faeren: Yes but this is just a small part of it. Most of it is underground since we get attacked a lot\n')
        sleep(long_delay)
        print('Penarrow: Who even attacks you i mean nobody knows about this place\n')
        sleep(long_delay)
        print('Faeren: Dragons and other creatures attack us\n')
        sleep(short_delay)
        print('Penarrow: Yeah, yeah as if\n')
        sleep(long_delay)
        print('Faeren: But it really is like that and we are unable to do anything against it\n')
        sleep(long_delay)
        print('But our legends say that one day a half-human is going to arrive and kill the dragon\n')
        sleep(long_delay)
        print('Luckily i am just a human and not some half-human\n')
        
        # Enter und Konsole clearen
        nextstep()
        
        print('Faeren: We will see.\n')
        sleep(short_delay)
        print('The legends also say that if you perform a certain ritual,\n')
        sleep(long_delay)
        print('you would gain special abilities\n')
        sleep(short_delay)
        print('Penarrow: What kind of abilities?\n')
        sleep(short_delay)
        print('Faeren: We do not know yet\n')
        sleep(short_delay)
        print('The legend has not taken place yet\n')
        sleep(long_delay)
        print('We were hoping that you could fulfill the ritual for us\n')
        sleep(short_delay)
        print('Penarrow: What does one have to do in those rituals?\n')
        sleep(short_delay)
        print('Faeren: You have to drink a special serum made out of our plants\n')
        sleep(short_delay)
        print('Penarrow: Thats it? Nothing more?\n')
        sleep(short_delay)
        print('Faeren: If you are the chosen one then yes\n')
        sleep(short_delay)
        print('Penarrow: And if not?\n')
        sleep(short_delay)
        print('Faeren: Then you die\n')
        sleep(short_delay)
        print('Penarrow: Do I have a choice?\n')
        sleep(short_delay)
        print('Faeren: Yes, you do\n')
        sleep(short_delay)
        print('Are you in for it?\n')
        sleep(short_delay)